### ISSUE TITLE
Nexus Version on Page shows 1.5.1

### ISSUE THREAD

**Issue by SocksTheWolf** [Enteligenz/StardewMods#12]
![image](https://github.com/Enteligenz/StardewMods/assets/132639882/be1f91a4-680b-4d03-899d-2061c4f2f31a)

But the file version is 1.5.5. I've never uploaded anything to Nexus so I don't know but I figured I'd give you a heads up.

**Comment by Enteligenz** [comment]
Strange... the file even shows the correct version. Anyway, I fixed it. Thanks for telling me.
