### ISSUE TITLE
GMCM Support?

### ISSUE THREAD

**Issue by SocksTheWolf** [Enteligenz/StardewMods#3]
Would it be worthwhile to add in support for GMCM so that the mod can be configured via in game?

https://github.com/spacechase0/StardewValleyMods/tree/develop/GenericModConfigMenu#for-c-mod-authors

**Comment by Enteligenz** [comment]
Possibly, yea. I don't really use the mod myself so I don't know what users might prefer. Though obviously, at the very least the password should not be editable through the menu ;)

**Comment by Enteligenz** [comment]
Does it support lists though, such as for the IgnoredAccounts option? I can't really find it.

**Comment by SocksTheWolf** [comment]
could add a string field that is manually exploded and repacked that is space separated/csv!

**Comment by SocksTheWolf** [comment]
![image](https://github.com/Enteligenz/StardewMods/assets/132639882/a33af9a8-cd7c-4b9b-ba98-eed3cbdbe89c)

I quickly cooked up this which I'll push in a pull request. You can change the values of the bots that you don't want and it properly restores back into an array. Obviously, if the array is just , then you'll have invalid garbage in the array config, but there's no negative issues there.

I added a password page which is hidden by default and also does not show up in the game (only main menu) where one can put in the OAuth token.

This works, but obviously you would need to restart for any connection changes. However this does make it like a billion times easier for general purpose audiences.

Could also add localization as well.

**Comment by Enteligenz** [comment]
That looks amazing :) I'll test it myself in a bit and take a look at localization, at least that's something I have done before.
Once more, thank you for your work!

**Comment by Enteligenz** [comment]
Ah, damn, you're quick. Just noticed you already threw in localization as a bonus. Well, I guess I can handle German localization :')

**Comment by SocksTheWolf** [comment]
The main major thing that could be done is to rework the initialization of TwitchBot to execute upon loading a save, rather than on initial entry into the application, allowing for the user to execute their config changes without a restart.

Maybe that's a task for a separate issue.

**Comment by Enteligenz** [comment]
Sounds reasonable, yea. I'll close this for now.

**Comment by SocksTheWolf** [comment]
I'll open a new issue for that.

**Comment by SocksTheWolf** [comment]
New issue in #5
