### ISSUE TITLE
Modify TwitchBot initialization

### ISSUE THREAD

**Issue by SocksTheWolf** [Enteligenz/StardewMods#5]
Right now the system initializes and executes in the mod's main entry loop, which on first time install, is before the config json is created. This ends up leaving users having to restart even after configuring, which can be confusing and also breaks GMCM's mantra that "configs can be changed without a restart".

If we modified the initialization to be during loading of a save, then we can have a more straightforward system that doesn't require user restarts.

**Comment by Enteligenz** [comment]
That would definitely make more sense, yup. I can look into it sometime, unless you were already intending to.
