### ISSUE TITLE
Adding support for USERNOTICE?

### ISSUE THREAD

**Issue by SocksTheWolf** [Enteligenz/StardewMods#8]
It might be handy to add USERNOTICE support so you can get alerted when someone subscribes/raids a channel.

https://dev.twitch.tv/docs/irc/commands/#usernotice

Would need to implement tag parsing to some degree. Anything to make this game more accessible for streamers.

**Comment by Enteligenz** [comment]
Tag Parsing? Did the messages we receive from Twitch have some sort of tagging, or do you mean getting the tags from the message text itself?

**Comment by SocksTheWolf** [comment]
> Tag Parsing? Did the messages we receive from Twitch have some sort of tagging, or do you mean getting the tags from the message text itself?

I believe it's located in the first portion of the space separated message. I'm not too sure how to get to it tbh. Perhaps have to tell the twitch server that we can support tag embedded messages?

**Comment by SocksTheWolf** [comment]
We have to request tag support via:

`CAP REQ :twitch.tv/commands twitch.tv/tags`

**Comment by Enteligenz** [comment]
Huh, I guess Twitch offers a surprising amount of info, if one just knows where to look

**Comment by SocksTheWolf** [comment]
They also have an example parser in js (which could be converted to C#) here https://dev.twitch.tv/docs/irc/example-parser/

**Comment by SocksTheWolf** [comment]
I went ahead and added tag requesting support and modified the offsets for finding the message/username/channel.

Would just need to add the USERNOTICE handling.

Should I open a pull request for just the tag stuff? I don't know if I'm going to add USERNOTICE unless I do it on stream today.

**Comment by Enteligenz** [comment]
Your call :) I'm not sure when I can find time to look at it myself anyway, been a while since I've touched anything Twitch-related, so there's no rush. And sorry about not having a lot of time for this rn, I feel like I'm letting you handle all this on your own :s

**Comment by SocksTheWolf** [comment]
No worries, I like working on accessibility stuff for streamers, and having everything in one window is really handy.
